[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
DATABASE_URL = "postgresql://postgres:newnew@db.bfaaznkamabozpiyjych.supabase.co:5432/postgres"
REPLIT_DOMAINS = "http://localhost:5000"
